print("---[Cobalt Launcher]---")
print("")
print("The Cobalt Launcher is under development and currently has no function.")
print("Current version: 0.1 Pre-Alpha")
print("")
print("Lead Developer: GrassyMoss")
print("Developer Comments: ''This launcher may not ever be developed''")
print("")
print("------")
print("\n")
input("Press Enter to close the Cobalt Launcher...")